name: CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  php-nuit:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:8.0.19
        ports:
          - 3306:3306
        options: --health-cmd "mysqladmin ping -h localhost" --health-interval 20s --health-timeout 10s --health-retries 10
        env:
          MYSQL_ROOT_PASSWORD: password
          MYSQL_DATABASE: ec

    env:
      DB_CONNECTION: mysql
      DB_HOST: 127.0.0.1
      DB_PORT: 3306
      DB_DATABASE: ec
      DB_USERNAME: root
      DB_PASSWORD: dbpj

    steps:
      - uses: actions/checkout@v2
      - name: Copy .env.testing
        run: cp .env.ci .env.testing
        working-directory: ./server
      - name: composer install
        run: |
          composer install --no-scripts
        working-directory: ./server
      - name: Generate key
        run: php artisan key:generate --env=testing
        working-directory: ./server
      - name: Directory Permissions
        run: chmod -R 777 storage bootstrap/cache
        working-directory: ./server
      - name: migrate
        run: php artisan migrate --env=testing
        working-directory: ./server
      - name: php-unit test
        run: ./vendor/bin/phpunit
        working-directory: ./serverComposer Install
        if: steps.cache.outputs.cache-hit != 'true'
        run: composer install -q --no-ansi --no-interaction --no-scripts --no-suggest --no-progress --prefer-dist

      - name: Composer Dump Autoload
        run: composer dump-autoload -q

      - name: Laravel Settings
        run: |
          cp .env.example .env
          php artisan key:generate
          php artisan optimize
          chmod -R 777 storage bootstrap/cache

      - name: Laravel Version
        run: php artisan --version

      - name: Laravel Migrate Testing
        run: php artisan migrate

      - name: Laravel Rollback Testing
        run: php artisan migrate:refresh

      - name: Laravel Seeding Testing
        run: php artisan db:seed

      - name: Laravel PHPUnit Testing
        run: |
          php artisan config:clear
          php artisan test
